/****************************************************************************
 The MIT License (MIT)

 Copyright (c) 2013 Apigee Corporation

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
 ****************************************************************************/
"use strict";

/*
 * This module implements the runtime SPI by storing data in redis.
 *
 * options:
 *   host:    redis host (optional, default = 127.0.0.1)
 *   port:    redis port (optional, default = 6379)
 *   options: redis options (optional, default = {})
 */

/*
token_details = {
  access_token: token,
  expires_in: ttl,
  scope: scope,
  application_id,
  developer_id
}

auth_details = {
 redirectUri: redirectUri,
 scope: scope
}

 schema:
 volos:oauth:access_token -> token_details
 volos:oauth:client_id:refresh_token -> token_details
 volos:oauth:client_id:auth_code -> auth_details
*/

var KEY_PREFIX = 'volos:oauth';
var CRYPTO_BYTES = 256 / 8;
var DEFAULT_TOKEN_LIFETIME = 60 * 60 * 24 * 1000; // 1 day in milliseconds
var REFRESH_TYPE = 'refresh';
var AUTH_TTL = 60 * 5; // 5 minutes

var querystring = require('querystring');
var crypto = require('crypto');
var redis = require("redis");
var OAuthCommon = require('volos-oauth-common');
var Management = require('volos-management-redis');
var Url = require('url');
var _ = require('underscore');

var debug;
var debugEnabled;
if (process.env.NODE_DEBUG && /apigee/.test(process.env.NODE_DEBUG)) {
  debug = function(x) {
    console.log('Apigee: ' + x);
  };
  debugEnabled = true;
} else {
  debug = function() { };
}

// clone & extend hash
var _extend = require('util')._extend;
function extend(a, b) {
  var options = _extend({}, a);
  options = _extend(options, b);
  return options;
}

var create = function(config) {
  var mgmt = Management.create(config);
  var spi = new RedisRuntimeSpi(mgmt, config);
  var oauth = new OAuthCommon(spi, config);
  return oauth;
};
module.exports.create = create;

var RedisRuntimeSpi = function(mgmt, config) {
  var host = config.host || '127.0.0.1';
  var port = config.port || 6379;
  var ropts = config.options || {};
  this.client = redis.createClient(port, host, ropts);
  this.mgmt = mgmt;
};

/*
 * Generate an access token using client_credentials. Parameters:
 *   clientId: required
 *   clientSecret: required
 *   scope: optional
 *   tokenLifetime: lifetime in milliseconds, optional
 *
 * Returns an object with all the fields in the standard OAuth 2.0 response.
 */
RedisRuntimeSpi.prototype.createTokenClientCredentials = function(options, cb) {
  options = extend(options, { type: 'client_credentials' });
  var self = this;
  this.mgmt.getAppIdForCredentials(options.clientId, options.clientSecret, function(err, reply) {
    if (err) { return cb(err); }
    if (!reply) { return cb(errorWithCode('invalid_client')); }
    createAndStoreToken(self, options, cb);
  });
};

/*
 * Generate an access token using password credentials. Parameters:
 *   clientId: required
 *   clientSecret: required
 *   scope: optional
 *   tokenLifetime: lifetime in milliseconds, optional
 *   username: required but not checked (must be checked outside this module)
 *   password: required by not checked (must be checked outside this module)
 *
 * Returns an object with all the fields in the standard OAuth 2.0 response.
 */
RedisRuntimeSpi.prototype.createTokenPasswordCredentials = function(options, cb) {
  options = extend(options, { type: 'password', refresh: true });
  createAndStoreToken(this, options, cb);
};

/*
 * Generate an access token for authorization code once a code has been set up. Parameters:
 *   clientId: required
 *   clientSecret: required
 *   code: Authorization code already generated by the "generateAuthorizationCode" method
 *   redirectUri: The same redirect URI that was set in the call to generate the authorization code
 *   tokenLifetime: lifetime in milliseconds, optional
 *
 * Returns an object with all the fields in the standard OAuth 2.0 response.
 */
RedisRuntimeSpi.prototype.createTokenAuthorizationCode = function(options, cb) {
  var self = this;
  consumeAuthCode(self.client, options.clientId, options.code, function(err, hash) {
    if (err) { return cb(err); }
    if (options.redirectUri !== hash.redirectUri) { return cb(invalidRequestError()); }
    options = extend(options, { type: 'authorization_code', refresh: true, scope: hash.scope });
    createAndStoreToken(self, options, cb);
  });
};

/*
 * Generate a redirect response for the authorization_code grant type. Parameters:
 *   clientId: required
 *   redirectUri: optional - if present, must match what was deployed along with the app
 *   scope: optional
 *   state: optional but certainly recommended
 *
 * Returns the redirect URI as a string.
 * 4.1.2
 */
RedisRuntimeSpi.prototype.generateAuthorizationCode = function(options, cb) {
  var self = this;
  self.mgmt.checkRedirectUri(options.clientId, options.redirectUri, function(err, redirectUri) {
    if (err) { return cb(err); }
    // past this point, errors must be part of the redirect uri
    createAndStoreAuthCode(self, options.clientId, options.scope, redirectUri, function(err, hash) {
      var qs = {};
      if (err) {
        qs.error = err.errorCode;
      } else {
        qs.code = hash.code;
        if (hash.scope) { qs.scope = hash.scope; }
      }
      if (options.state) { qs.state = options.state; }
      var url = Url.parse(redirectUri, true);
      url.query = extend(url.query, qs);
      var uri = Url.format(url);
      return cb(null, uri);
    });
  });
};

/*
 * Generate a redirect response for the implicit grant type. Parameters:
 *   clientId: required
 *   redirectUri: optional - if present, must match what was deployed along with the app
 *   scope: optional
 *   state: optional but certainly recommended
 *
 * Returns the redirect URI as a string.
 */
RedisRuntimeSpi.prototype.createTokenImplicitGrant = function(options, cb) {
  var self = this;
  this.mgmt.checkRedirectUri(options.clientId, options.redirectUri, function(err, redirectUri) {
    if (err) { return cb(err); }
    // past this point, errors must be part of the redirect uri
    options = extend(options, { type: 'authorization_code', refresh: false});
    createAndStoreToken(self, options, function(err, reply) {
      var qs = {};
      if (err) {
        qs.error = err.errorCode;
      } else {
        qs = { access_token: reply.access_token, expires_in: reply.expires_in };
        if (reply.scope) { qs.scope = reply.scope; }
      }
      if (options.state) { qs.state = options.state; }
      var url = Url.parse(redirectUri, true);
      url.query = extend(url.query, qs);
      url.hash = querystring.stringify(url.query);
      url.query = null;
      var uri = Url.format(url);
      return cb(null, uri);
    });
  });
};

/*
 * Refresh an existing access token, and return a new token. Parameters:
 *   clientId: required
 *   clientSecret: required
 *   refreshToken: required, from the original token grant
 */
RedisRuntimeSpi.prototype.refreshToken = function(options, cb) {
  var self = this;
  self.client.get(_key(options.clientId, options.refreshToken), function(err, reply) {
    if (err) { return cb(err); }
    if (reply) {
      var token = JSON.parse(reply);
      options.scope = token.scope;
      createAndStoreToken(self, options, function(err, reply) {
        if (err) { return cb(err); }
        self.client.del(_key(options.refreshToken)); // note: async, ignores reply
        return cb(null, reply);
      });
    } else {
      return cb(invalidRequestError());
    }
  });
};

/*
 * Invalidate an existing token. Parameters:
 *   clientId: required
 *   clientSecret: required
 *   refreshToken: either this or accessToken must be specified
 *   accessToken: same
 */
RedisRuntimeSpi.prototype.invalidateToken = function(options, cb) {
  // check clientId, clientSecret
  this.mgmt.getAppIdForCredentials(options.clientId, options.clientSecret, function(err, reply) {
    if (err) { return cb(err); }
    if (!reply) { return cb(invalidRequestError()); }
  });
  if (options.token) { this.client.del(_key(options.token)); }
  if (options.refreshToken) { this.client.del(_key(options.refreshToken)); }
  return cb(null, 'OK');
};

/*
 * Validate an access token. Specify just the token and we are fine.
 */
RedisRuntimeSpi.prototype.verifyToken = function(token, verb, path, cb) {
  var self = this;
  self.client.get(_key(token), function(err, reply) {
    if (err || !reply) {
      return cb(invalidRequestError());
    } else {
      var token_details = JSON.parse(reply);
      self.mgmt.scopesMatching(token_details.application_id, verb, path, function(err, requiredScopes) {
        if (err) { return cb(err); }
        if (requiredScopes) {
          var grantedScopes = token_details.scope.split(' ');
          if (_.difference(requiredScopes, grantedScopes).length > 0) {
            cb(errorWithCode('invalid_scope'));
          }
        }
        var result = { appId: token_details.application_id, developerId: token_details.developerId };
        return cb(null, result);
      });
    }
  });
};

// utility functions

function createAndStoreAuthCode(self, clientId, requestedScope, redirectUri, cb) {
  self.mgmt.getAppForClientId(clientId, function(err, app) {
    if (err) { return cb(err); }

    determineGrantedScope(requestedScope, app, function(err, grantedScope) {
      if (err) { return cb(err); }

      var code = genSecureToken();
      var hash = JSON.stringify({ redirectUri: redirectUri, scope: grantedScope });
      self.client.setex(_key(clientId, code), AUTH_TTL, hash, function(err, reply) {
        if (err) { return err; }
        return cb(null, { code: code, scope: grantedScope });
      });
    });
  });
}

function consumeAuthCode(client, clientId, code, cb) {
  client.get(_key(clientId, code), function(err, hash) {
    if (err) { return cb(err); }
    if (!hash) { return cb(invalidRequestError()); }
    client.del(_key(clientId, code), function(err, reply) {
      return cb(err, JSON.parse(hash));
    });
  });
}

/* options: {
 *   clientId: required
 *   clientSecret: required, unless type === 'authorization_code' || type == 'password'
 *   scope: optional
 *   tokenLifetime: lifetime in milliseconds, optional
 *   type: required
 *   refresh: optional (default: false)
 *   }
 */
function createAndStoreToken(self, options, cb) {
  getAppForOptions(self, options, function(err, app) {
    if (err || !app) { return cb(errorWithCode('access_denied')); }

    determineGrantedScope(options.scope, app, function(err, grantedScope) {
      if (err) { return cb(err); }

      var ttl = options.tokenLifetime ? (options.tokenLifetime / 1000) : DEFAULT_TOKEN_LIFETIME;
      var token = genSecureToken();
      storeToken(self.client, app, token, options.type, options.clientId, ttl, grantedScope, function(err, reply) {
        var tokenResponse = reply;
        if (err) { return cb(err); }
        if (options.refresh) {
          var refreshToken = genSecureToken();
          storeRefreshToken(self.client, app, refreshToken, options.clientId, grantedScope, function(err, reply) {
            if (err) { return cb(err); }
            tokenResponse.refresh_token = refreshToken;
            return cb(null, tokenResponse);
          });
        } else {
          return cb(null, tokenResponse);
        }
      });
    });
  });
}

function getAppForOptions(self, options, cb) {
  if (!options.clientSecret && (options.type === 'authorization_code' || options.type === 'password')) {
    self.mgmt.getAppForClientId(options.clientId, cb);
  } else {
    self.mgmt.getAppForCredentials(options.clientId, options.clientSecret, cb);
  }
}

// given a requested scope, returns granted scopes
// grants what it can, ignores what it can't. but if no default and no match, fails.
function determineGrantedScope(requestedScope, app, cb) {
  if (!requestedScope) { return cb(null, app.defaultScope); }
  if (!app.scopes) { return cb(null, null); }
  var requestedScopes = requestedScope.split(' ');
  var grantedScopes = _.intersection(requestedScopes, app.scopes);
  if (grantedScopes.length === 0) {
    if (!app.defaultScope) { return cb(errorWithCode('invalid_scope')); }
    grantedScopes.push(app.defaultScope);
  }
  return cb(null, grantedScopes.join(' '));
}

function invalidRequestError() {
  return errorWithCode('invalid_request');
}

function genSecureToken() {
  return crypto.randomBytes(CRYPTO_BYTES).toString('base64');
}

function storeToken(client, app, token, type, clientId, ttl, scope, cb) {
  var response = {
    access_token: token,
    expires_in: ttl,
    scope: scope
  };
  if (scope) { response.scope = scope; }
  var stored = JSON.stringify(_.extend({ application_id: app.id }, response));
  var key = (type === REFRESH_TYPE) ? _key(clientId, token) :_key(token);
  if (ttl) {
    client.setex(key, ttl, stored, function(err, reply) {
      return cb(err, response);
    });
  } else {
    client.set(key, stored, function(err, reply) {
      return cb(err, response);
    });
  }
}

function storeRefreshToken(client, app, token, clientId, scope, cb) {
  storeToken(client, app, token, REFRESH_TYPE, clientId, null, scope, cb);
}

function _key() {
  var argsArray = [].slice.apply(arguments);
  argsArray.unshift(KEY_PREFIX);
  return argsArray.join(':');
}

function errorWithCode(code) {
  var err = new Error(code);
  err.errorCode = code;
  return err;
}
